name: Debugging workflow
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Testing awk / UTF-8
        run: awk 'BEGIN {print length("héé");}'
      - name: Testing iconv
        run: command -v iconv
      - name: Testing the ps command (with $$)
        run: ps $$
      - name: Testing the ps command (with -p $$)
        run: ps -p $$
      - name: Testing the ps command (no argument)
        run: ps
